# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=1.0.1-alpha
group=org.IFBX.isekaiGateway
java_version=21

# Common
minecraft_version=1.21.1
mod_name=isekai-backend-modern
mod_author=m3t4lm0uth
mod_id=isekai-backend-modern
license=GPL-3.0
credits=
description=backend infra for velocity plugin
minecraft_version_range=[1.21, 1.22)
neo_form_version=1.21-20240613.152323
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21
parchment_version=2024.06.23

# Fabric
fabric_version=0.116.9+1.21.1
fabric_loader_version=0.18.4
yarn_mappings=1.21.1+build.3

# Forge
forge_version=52.1.10
forge_loader_version_range=[52,)

# NeoForge
neoforge_version=21.0.37-beta
neoforge_loader_version_range=[4,)

